name: jci_manila_v2
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  file_picker: ^9.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  geolocator: ^13.0.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  html: ^0.15.5
  http: ^1.3.0
  intl: ^0.20.2
  permission_handler: ^11.4.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  provider: ^6.1.2
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.jpg"
  adaptive_icon_foreground: "assets/icons/app_logo.jpg"
