class UserProfile {
  String name;
  String lastName;
  String firstName;
  int status;
  dynamic preGmm;
  String contactNumber;
  String email;
  dynamic company;
  dynamic shippingAddress1;
  dynamic shippingAddress2;
  dynamic shippingCity;
  dynamic shippingZip;
  int freeGmm;
  String membership;
  int id;
  int membershipDue;
  int penalty;
  DateTime bday;
  String verificationStatus;
  DateTime dateAdded;
  String nickname;
  dynamic sponsor;
  dynamic memberId;
  dynamic currentAge;
  String schoolGraduated;
  String profession;
  String industry;
  String resume;
  String homeAddress;
  dynamic bjcProjectTitle;
  dynamic inductionDate;
  dynamic purpose;
  dynamic wantedChairman;
  dynamic personalityType;
  dynamic careGroup;
  dynamic uloDate;
  dynamic uloEvent;
  dynamic launchpad;
  dynamic launchPadDate;
  dynamic projectClosingDate;
  dynamic photo;
  dynamic uploadPhoto;
  dynamic bjcProjectPresentationDate;
  dynamic active;
  dynamic resetToken;
  dynamic resetDate;
  dynamic pannelStatus;
  dynamic pannelsRemarks;
  dynamic sponsorName;
  dynamic civilStatus;
  dynamic contactNo2;
  dynamic educationalAttaiment;
  dynamic highSchool;
  dynamic homeContactNo;
  dynamic employmentStatus;
  dynamic officeAddress;
  dynamic officeContactNo;
  dynamic jciPhilId;
  dynamic jciSenNo;
  dynamic telNoFax;
  dynamic alternateEmail;
  dynamic spouseName;
  dynamic spouseContactNo;
  dynamic sports;
  dynamic interest;
  dynamic aboutYourSelf;
  dynamic awardsReceived;
  dynamic currentPosition;
  dynamic currentPositionDirectorate;
  dynamic previousProjects;
  dynamic contactPerson;
  dynamic contactPersonRelationship;
  dynamic otherSkills;
  dynamic facebook;
  dynamic instragram;
  dynamic twitter;
  dynamic linkedin;
  int showBday;
  int showProfessionInfo;
  int showProfile;
  int showPrimaryContactInfo;
  int showSecondaryContactInfo;
  int showAddress;
  int showCivilStatus;
  int showEducationInfo;
  int showInterestSkills;
  int showSocialMedia;
  dynamic showJciJourney;
  int showJciProjects;
  int showEventsAttended;
  dynamic vaccineCard;
  dynamic uploadVacineCard;
  dynamic yearInducted;
  dynamic course;
  dynamic jciAreaConferenceEvents;
  dynamic homeCity;
  dynamic officeCity;
  dynamic membershipBenefits;
  dynamic boardOfDirector;
  dynamic commissionership;
  dynamic jcipNationalConvention;
  dynamic jciAsiaPacificConference;
  dynamic jciWorldCongress;
  dynamic emergencyLastName;
  dynamic emergencyFirstName;
  dynamic emergencyMiddleName;
  dynamic emeregencyMobileNumber;
  dynamic yearInductedBaby;
  dynamic chairmanship;
  dynamic emergencyRelationship;
  dynamic middleName;
  dynamic contactPersonNumber;
  dynamic applicationGroup;
  dynamic applicationRemarks;
  dynamic applicantStatus;
  int bod;
  dynamic inductionDateBabyJc;
  dynamic position;
  dynamic currentTitle;
  dynamic bioFace;
  dynamic bioFinger;
  dynamic emailOtp;
  int sponsorType;
  int mobileRegister;
  int showNotifications;
  int memberPoints;
  int projectsCount;
  int eventsCount;

  UserProfile({
    required this.name,
    required this.lastName,
    required this.firstName,
    required this.status,
    required this.preGmm,
    required this.contactNumber,
    required this.email,
    required this.company,
    required this.shippingAddress1,
    required this.shippingAddress2,
    required this.shippingCity,
    required this.shippingZip,
    required this.freeGmm,
    required this.membership,
    required this.id,
    required this.membershipDue,
    required this.penalty,
    required this.bday,
    required this.verificationStatus,
    required this.dateAdded,
    required this.nickname,
    required this.sponsor,
    required this.memberId,
    required this.currentAge,
    required this.schoolGraduated,
    required this.profession,
    required this.industry,
    required this.resume,
    required this.homeAddress,
    required this.bjcProjectTitle,
    required this.inductionDate,
    required this.purpose,
    required this.wantedChairman,
    required this.personalityType,
    required this.careGroup,
    required this.uloDate,
    required this.uloEvent,
    required this.launchpad,
    required this.launchPadDate,
    required this.projectClosingDate,
    required this.photo,
    required this.uploadPhoto,
    required this.bjcProjectPresentationDate,
    required this.active,
    required this.resetToken,
    required this.resetDate,
    required this.pannelStatus,
    required this.pannelsRemarks,
    required this.sponsorName,
    required this.civilStatus,
    required this.contactNo2,
    required this.educationalAttaiment,
    required this.highSchool,
    required this.homeContactNo,
    required this.employmentStatus,
    required this.officeAddress,
    required this.officeContactNo,
    required this.jciPhilId,
    required this.jciSenNo,
    required this.telNoFax,
    required this.alternateEmail,
    required this.spouseName,
    required this.spouseContactNo,
    required this.sports,
    required this.interest,
    required this.aboutYourSelf,
    required this.awardsReceived,
    required this.currentPosition,
    required this.currentPositionDirectorate,
    required this.previousProjects,
    required this.contactPerson,
    required this.contactPersonRelationship,
    required this.otherSkills,
    required this.facebook,
    required this.instragram,
    required this.twitter,
    required this.linkedin,
    required this.showBday,
    required this.showProfessionInfo,
    required this.showProfile,
    required this.showPrimaryContactInfo,
    required this.showSecondaryContactInfo,
    required this.showAddress,
    required this.showCivilStatus,
    required this.showEducationInfo,
    required this.showInterestSkills,
    required this.showSocialMedia,
    required this.showJciJourney,
    required this.showJciProjects,
    required this.showEventsAttended,
    required this.vaccineCard,
    required this.uploadVacineCard,
    required this.yearInducted,
    required this.course,
    required this.jciAreaConferenceEvents,
    required this.homeCity,
    required this.officeCity,
    required this.membershipBenefits,
    required this.boardOfDirector,
    required this.commissionership,
    required this.jcipNationalConvention,
    required this.jciAsiaPacificConference,
    required this.jciWorldCongress,
    required this.emergencyLastName,
    required this.emergencyFirstName,
    required this.emergencyMiddleName,
    required this.emeregencyMobileNumber,
    required this.yearInductedBaby,
    required this.chairmanship,
    required this.emergencyRelationship,
    required this.middleName,
    required this.contactPersonNumber,
    required this.applicationGroup,
    required this.applicationRemarks,
    required this.applicantStatus,
    required this.bod,
    required this.inductionDateBabyJc,
    required this.position,
    required this.currentTitle,
    required this.bioFace,
    required this.bioFinger,
    required this.emailOtp,
    required this.sponsorType,
    required this.mobileRegister,
    required this.showNotifications,
    required this.memberPoints,
    required this.projectsCount,
    required this.eventsCount,
  });

  factory UserProfile.fromJson(Map<String, dynamic> json) => UserProfile(
    name: json["name"],
    lastName: json["last_name"],
    firstName: json["first_name"],
    status: json["status"],
    preGmm: json["pre_gmm"],
    contactNumber: json["contact_number"],
    email: json["email"],
    company: json["company"],
    shippingAddress1: json["shipping_address1"],
    shippingAddress2: json["shipping_address2"],
    shippingCity: json["shipping_city"],
    shippingZip: json["shipping_zip"],
    freeGmm: json["free_gmm"],
    membership: json["membership"],
    id: json["id"],
    membershipDue: json["membership_due"],
    penalty: json["penalty"],
    bday: DateTime.parse(json["bday"]),
    verificationStatus: json["verification_status"],
    dateAdded: DateTime.parse(json["date_added"]),
    nickname: json["nickname"],
    sponsor: json["sponsor"],
    memberId: json["member_id"],
    currentAge: json["current_age"],
    schoolGraduated: json["school_graduated"],
    profession: json["profession"],
    industry: json["industry"],
    resume: json["resume"],
    homeAddress: json["home_address"],
    bjcProjectTitle: json["bjc_project_title"],
    inductionDate: json["induction_date"],
    purpose: json["purpose"],
    wantedChairman: json["wanted_chairman"],
    personalityType: json["personality_type"],
    careGroup: json["care_group"],
    uloDate: json["ulo_date"],
    uloEvent: json["ulo_event"],
    launchpad: json["launchpad"],
    launchPadDate: json["launch_pad_date"],
    projectClosingDate: json["project_closing_date"],
    photo: json["photo"],
    uploadPhoto: json["upload_photo"],
    bjcProjectPresentationDate: json["bjc_project_presentation_date"],
    active: json["active"],
    resetToken: json["reset_token"],
    resetDate: json["reset_date"],
    pannelStatus: json["pannel_status"],
    pannelsRemarks: json["pannels_remarks"],
    sponsorName: json["sponsor_name"],
    civilStatus: json["civil_status"],
    contactNo2: json["contact_no2"],
    educationalAttaiment: json["educational_attaiment"],
    highSchool: json["high_school"],
    homeContactNo: json["home_contact_no"],
    employmentStatus: json["employment_status"],
    officeAddress: json["office_address"],
    officeContactNo: json["office_contact_no"],
    jciPhilId: json["jci_phil_id"],
    jciSenNo: json["jci_sen_no"],
    telNoFax: json["tel_no_fax"],
    alternateEmail: json["alternate_email"],
    spouseName: json["spouse_name"],
    spouseContactNo: json["spouse_contact_no"],
    sports: json["sports"],
    interest: json["interest"],
    aboutYourSelf: json["about_your_self"],
    awardsReceived: json["awards_received"],
    currentPosition: json["current_position"],
    currentPositionDirectorate: json["current_position_directorate"],
    previousProjects: json["previous_projects"],
    contactPerson: json["contact_person"],
    contactPersonRelationship: json["contact_person_relationship"],
    otherSkills: json["other_skills"],
    facebook: json["facebook"],
    instragram: json["instragram"],
    twitter: json["twitter"],
    linkedin: json["linkedin"],
    showBday: json["show_bday"],
    showProfessionInfo: json["show_profession_info"],
    showProfile: json["show_profile"],
    showPrimaryContactInfo: json["show_primary_contact_info"],
    showSecondaryContactInfo: json["show_secondary_contact_info"],
    showAddress: json["show_address"],
    showCivilStatus: json["show_civil_status"],
    showEducationInfo: json["show_education_info"],
    showInterestSkills: json["show_interest_skills"],
    showSocialMedia: json["show_social_media"],
    showJciJourney: json["show_jci_journey"],
    showJciProjects: json["show_jci_projects"],
    showEventsAttended: json["show_events_attended"],
    vaccineCard: json["vaccine_card"],
    uploadVacineCard: json["upload_vacine_card"],
    yearInducted: json["year_inducted"],
    course: json["course"],
    jciAreaConferenceEvents: json["jci_area_conference_events"],
    homeCity: json["home_city"],
    officeCity: json["office_city"],
    membershipBenefits: json["membership_benefits"],
    boardOfDirector: json["board_of_director"],
    commissionership: json["commissionership"],
    jcipNationalConvention: json["jcip_national_convention"],
    jciAsiaPacificConference: json["jci_asia_pacific_conference"],
    jciWorldCongress: json["jci_world_congress"],
    emergencyLastName: json["emergency_last_name"],
    emergencyFirstName: json["emergency_first_name"],
    emergencyMiddleName: json["emergency_middle_name"],
    emeregencyMobileNumber: json["emeregency_mobile_number"],
    yearInductedBaby: json["year_inducted_baby"],
    chairmanship: json["chairmanship"],
    emergencyRelationship: json["emergency_relationship"],
    middleName: json["middle_name"],
    contactPersonNumber: json["contact_person_number"],
    applicationGroup: json["application_group"],
    applicationRemarks: json["application_remarks"],
    applicantStatus: json["applicant_status"],
    bod: json["bod"],
    inductionDateBabyJc: json["induction_date_baby_jc"],
    position: json["position"],
    currentTitle: json["current_title"],
    bioFace: json["bio_face"],
    bioFinger: json["bio_finger"],
    emailOtp: json["email_otp"],
    sponsorType: json["sponsor_type"],
    mobileRegister: json["mobile_register"],
    showNotifications: json["show_notifications"],
    memberPoints: json["member_points"],
    projectsCount: json["projects_count"],
    eventsCount: json["events_count"],
  );
}
